#if !canImport(ObjectiveC)
import XCTest

extension SocketConnectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SocketConnectionTests = [
        ("testCanConnectToImapServer", testCanConnectToImapServer),
        ("testCanDetectDisconnectFromServer", testCanDetectDisconnectFromServer),
        ("testCanReadFromServer", testCanReadFromServer),
        ("testCanWriteToServer", testCanWriteToServer),
        ("testReadingFromNetworkIndicatorChangesOnRead", testReadingFromNetworkIndicatorChangesOnRead),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SocketConnectionTests.__allTests__SocketConnectionTests),
    ]
}
#endif
